kind: wasmer.io/App.v0
name: wordpress
owner: wasmer-examples
package: .
scaling:
  mode: single_concurrency
capabilities:
  instaboot:
    max_age: 59m
    requests:
    - path: /
      headers:
      - name: Accept
        value: text/html
      - name: Accept-Language
        value: en-US
    - path: /
      headers:
      - name: Accept
        value: text/html
      - name: Accept-Language
        value: en-US
    - path: /
      headers:
      - name: Accept
        value: text/html
      - name: Accept-Language
        value: en-US
    - path: /
      headers:
      - name: Accept
        value: text/html
      - name: Accept-Language
        value: en-US
