[dependencies]
"php/php" = "8.3.4"

[fs]
"/app" = "app"
"/db" = "db"

[[command]]
name = "run"
module = "php/php:php"
runner = "wasi"

[command.annotations.wasi]
main-args = ["-t", "/app", "-S", "localhost:8080"]
env = ["PHPRC=/config/php.ini"]
