[package]
name = "wasmer-examples/wordpress-wasmer-starter"
version = "0.2.4"
description = "Wordpress starter package"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/wasmer-examples/wordpress-wasmer-starter"
entrypoint = "run"

[dependencies]
"arshia001/php" = "=8.3.4-pre.4"

[fs]
"/app" = "app"
"/db" = "db"

[[command]]
name = "run"
module = "arshia001/php:php"
runner = "wasi"

[command.annotations.wasi]
main-args = ["-t", "/app", "-S", "localhost:8080"]
